Resources:
    mylaunch:
      Type: AWS::EC2::Instance
      Properties:
        ImageId: ami-07bff6261f14c3a45
        InstanceType: t2.micro
        KeyName: challenge
        PropagateTagsToVolumeOnCreation: "true"
        Tags: 
        - Key: Name
          Value: python_01
