Resources:
    mylaunch:
      Type: AWS::EC2::Instance
      Properties:
        ImageId: ami-07bff6261f14c3a45
        InstanceType: t2.micro
        KeyName: challenge
        PropagateTagsToVolumeOnCreation: "true"
        Tags: 
          - Key: Name
            Value: python_01
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash
            dnf update -y
            dnf install docker -y
            systemctl start docker
            systemctl enable docker
Outputs:
  InstancePublicDNS:
    Description: "The Public DNS Name of the instance"
    Value: !GetAtt mylaunch.PublicDnsName
    Export:
      Name: InstancePublicDNSName