name: build and push docker image
#name of workflow. This workflow will build and push a docker image to docker hub.

on:
  push:
    branches:
      - 'main'
      #tell github actions to act when a push is made on the 'main' branch.

  workflow_dispatch:
    branches:
      - 'main'
      #allows to push workflow manually from github.
       
jobs:
  dockerpush:
    runs-on: ubuntu-latest
    #tell github actions to run a job named dockerpush using a runner on the latest version of ubuntu.

    steps: #lists steps for github actions to complete
      - name: checkout code
        uses: actions/checkout@v4
        #name is a desription of the action, uses: tells github which action to use from the marketplace. checkout v4 will clone the repo to the runner.

      - name: set up docker buildx
        uses: docker/setup-buildx-action@v3
        #this action will create and boot a builder that can be used to build an image.

      - name: login to dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        #gitHub action to login against a docker registry. the username and password are stored in github actions secrets and variables for security.

      - name: build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/container_challenge:latest
          secrets: |
            AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
        #GitHub Action to build and push Docker images with Buildx. 



